# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application's code
COPY main.py .

# The command that will be run when the container starts
# This tells the Lambda service to use the 'handler' object in the 'main' module
CMD ["main.handler"]
